language: php  # 我们代码所需要运行的环境平台

php:  # 需要测试的版本
  - 7.4
  - 8.0

dist: focal  # 系统版本
sudo: false  # 是否使用 sudo 模式

matrix:
  include:
    - php: 7.2
      dist: trusty
    - php: 7.3
      dist: trusty

# 执行前需要运行的命令
install: travis_retry composer install --no-interaction --prefer-source

# 主要构建命令
script: vendor/bin/phpunit --verbose

